

export ZSH=$HOME/.oh-my-zsh

if [ -d "/usr/share/oh-my-zsh" ]
then
	export ZSH="/usr/share/oh-my-zsh"
fi


if [ -d "$ZSH" ]
then

	ZSH_THEME=
	
	zstyle ':omz:update' mode reminder  # just remind me to update when it's time
	zstyle ':omz:update' frequency 14

	plugins=(
		git git-extras 
		archlinux 
		adb 
	)
#	source $ZSH/oh-my-zsh.sh
	export ARCHFLAGS="-arch x86_64"
fi



HIST_STAMPS="yyyy/mm/dd"


if [ -f /usr/bin/oh-my-posh ]
then
	eval "$(oh-my-posh init zsh --config $HOME/.config/zsh/oh-my-posh/pure.omp.json)"
fi


if [ -f /usr/share/zsh/plugins/fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh ]
then
  source /usr/share/zsh/plugins/fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh
fi

if [ -f /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh ]
then
  source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
fi

if [ -f /usr/share/zsh/plugins/zsh-autocomplete/zsh-autocomplete.plugin.zsh ]
then
	source /usr/share/zsh/plugins/zsh-autocomplete/zsh-autocomplete.plugin.zsh
	
	bindkey '^I' menu-select

	bindkey -M menuselect '^[[D' .backward-char '^[OD' .backward-char
	bindkey -M menuselect '^[[C' .forward-char '^[OC' .forward-char

fi


source $HOME/.config/zsh/config.zsh
