if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

export ZSH="/usr/share/oh-my-zsh"


ZSH_THEME=



zstyle ':omz:update' mode reminder  # just remind me to update when it's time

zstyle ':omz:update' frequency 14


HIST_STAMPS="yyyy/mm/dd"


plugins=(
    git git-extras 
    archlinux 
    adb 
)

source $ZSH/oh-my-zsh.sh

export ARCHFLAGS="-arch x86_64"

source $HOME/.config/zsh/config.zsh


# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.

source /usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh


if [ -f /usr/share/zsh/plugins/fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh ]; then
  source /usr/share/zsh/plugins/fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh
fi

if [ -f /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh ]; then
  source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
fi

PLE () {
  # Go to the saved directory
  cd "/home/opticxc/projects/android/Pixel-Launcher-Extended"

  # Check if builder.sh exists
  if [ -f builder.sh ]; then
    chmod +x builder.sh && ./builder.sh
  else
    echo "PLE Builder is not available in your system"
  fi

  # Go back to the home folder
  cd ~
}
