#! /bin/bash

echo "Making cache directory"
CACHE_DIR=$HOME/.cache/bootstrap
mkdir -p $CACHE_DIR


install_package(){
    echo "Installing $1"
	sudo paru -S $1 --noconfirm
}

if [ ! -f /sbin/paru ]; then
    echo "Installing Paru"
    if [ ! -f /sbin/git ]; then
	    install_package git
    fi
    git clone https://aur.archlinux.org/paru-bin.git $CACHE_DIR/paru-bin
    cd $CACHE_DIR/paru-bin
    makepkg -si --noconfirm
fi
echo "Using Paru as package manager"

echo "Checking supported micro-architecture"
microarch=$(/usr/lib/ld-linux-x86-64.so.2 --help | grep 'supported' | awk 'NR==1 {print $1}')
echo "Detected micro-architecture: $microarch"

enable_alhp="n"
read -p "Do you want to enable ALHP repos? (y/N)" enable_alhp

if [ "$enable_alhp" = "y" ]; then
	~/.config/yadm/scripts/enable_alhp.sh $microarch
fi


enable_chaotic="n"
read -p "Do you want to enable Chaotic Aur  repos? (y/N)" enable_chaotic

if [ "$enable_chaotic" = "y" ]; then
	paru -S chaotic-keyring chaotic-mirrorlist --noconfim
fi

bash -c "$HOME/.config/yadm/scripts/setup_root.sh"



echo "Updating pacman database"
sudo pacman -Sy
echo "Updating pacman Filelist"
sudo pacman -Fy

echo "Installing packages"
paru -S --noconfirm - < $HOME/.config/yadm/pkglist.txt
paru -S --noconfirm - < $HOME/.config/yadm/pkglist_aur.txt


enable_imp = n

read -p "Install illogical impulse packages? (y/N) "



if [ "$enable_imp" = "y" ]; then
	echo "Installing Illogical-Impulse patched pkgs"
	~/.config/yadm/scripts/install-illogical.sh
	echo "Installed Illogical impulse packages"
fi
