#! /usr/bin/bash

# Start waybar with custom config and style
# This script is meant to be used with the hyprctl tool


user=$(whoami)
runtime_dir="/tmp/waybar-$user"



conf_dir="$HOME/.config/waybar"
config="$conf_dir/config.jsonc"


style_sass="$conf_dir/style.sass"
style_css="$runtime_dir/style.css"


killall waybar


mkdir -p "$runtime_dir"

sass --update -I $HOME/.cache/wal  "$style_sass" "$style_css"

waybar -c "$config" -s "$style_css" & disown

