CompilerFlags:
  Add: [ -xc++, -Wall, -Wextra, -Werror, -I=/usr/include ]


Diagnostics:
  ClangTidy:
    Add: modernize*

  UnusedIncludes: Strict

  InlayHints:
    Designators: Yes
    Enabled: Yes

