

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
blink_interval = 550
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "xterm-256color"


[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[terminal.shell]
program = "/usr/bin/fish"


[window]
opacity = 0.90
padding = { x = 10, y = 10 }
dynamic_padding = true
dynamic_title = true


[keyboard]
bindings = [
	{ mods = "Super|Shift", key = "Return", action = "SpawnNewInstance" }

]

[general]
live_config_reload = true
import = ["~/.config/alacritty/colors-material.toml", "~/.config/alacritty/fonts.toml"]

[terminal]


[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
regex =  "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"

[debug]
render_timer = false
persistent_logging = true
log_level = "Warn"
