[font]
size = 12

[font.bold]
family = "JetBrainsMono Nerd Font Propo"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Propo"

[font.italic]
family = "JetBrainsMono Nerd Font Propo"

[font.normal]
family = "JetBrainsMono Nerd Font Propo"
